#!/bin/bash

#SBATCH --job-name=2D_sbatch
#SBATCH --output=2D_sbatch.out
#SBATCH --error=2D_sbatch.err
#SBATCH --time=00:05:00
#SBATCH --partition=caslake
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=48
#SBATCH --mem-per-cpu=2000

# Set OMP_NUM_TREADS to the number of CPUs per task we asked for
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

module load openmpi
mpirun --bind-to none --report-bindings ./2D_grid

