#!/bin/bash

#SBATCH --job-name=1D_sbatch
#SBATCH --output=1D_sbatch.out
#SBATCH --error=1D_sbatch.err
#SBATCH --time=00:05:00
#SBATCH --partition=caslake
#SBATCH --nodes=32
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000


mpirun ./parallel 2048

